Fix for redhat-developer/vscode-yaml#353, error when editing yaml wit…
redhat-developer/yaml-language-server pull request #309
Opened 2020-08-20 21:57 UTC by JPinkney

…h comments

This PR should fix https://github.com/redhat-developer/vscode-yaml/issues/353.

This is occurring because https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/yamlParser07.ts#L125 is incrementing yamlDocCount by 1 when `---` is the first thing present in the YAML file. Then when https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/yamlParser07.ts#L129 is hit yamlDocs[1] will be undefined when there is only a single YAML document, thus creating the error.

The solution is to only increment yamlDocCount when you see `---` and it's not the first line of the file. That way these two instances (with and without `---` at the start get parsed correctly)
```
# some comment
test: test
...
```
and
```
---
# some comment
test: test
...
```

Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

2020-08-21 01:17 UTC, gorkem commented on src/languageservice/parser/yamlParser07.ts
> +    if (line === YAML_DATA_INSTANCE_SEPARATOR && index !== 0) {
index > 0 is probably safer

2020-08-27 01:21 UTC, JPinkney commented
Moving this out of WIP, @apupier can you take a look again

2020-08-27 02:36 UTC, charlesguo404 commented
LGTM

2020-08-27 07:09 UTC, apupier requested changes
minor stuff that would be nice to change before merging

- constant 'YAML_DIRECTIVE_PREFIX' is no more used and thus an be removed

2020-08-27 07:09 UTC, apupier commented on src/languageservice/parser/yamlParser07.ts
> +  let firstSeperatorFound = false;
typo seperator -> separator

2020-08-27 12:38 UTC, apupier approved these changes

2020-08-27 12:46 UTC, merged