New completion
redhat-developer/yaml-language-server pull request #525
Opened 2021-08-19 11:17 UTC by evidolob

### What does this PR do?
This PR add usage of new AST for code completion, now code completion uses raw AST(without converting it to JSON compatible AST)  
Basically it is not completely rewrite, it is a port of old code completion to new AST. 
Also to be able select proper JSON Schema I port validation code to new AST(`json-schema07-validator.ts`).
So we can remove AST convert completely( delete `ast-converter.ts` and all related code/types).

### What issues does this PR fix or reference?
Resolve #517

### Is it tested? How?
With tests

2021-08-21 16:35 UTC, gorkem requested changes
Something is not working right with this version. When I use this version of the LS on vscode-yaml, the errors are not cleaned after I fix them until I reopen the editor. 

Also it is it is very hard to identify what to review on this PR because it is mixed with some of the main changes that are coming from main.  Can we seperate the main merge ?

2021-08-23 12:33 UTC, evidolob commented
@evidolob I fix validation, now it should work.

2021-08-27 23:53 UTC, gorkem requested changes
I should still do a bit more testing but functionality seems to be in place. It would be great if we can add tests to the new functions introduced. Otherwise I have some minor comments

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/services/yamlValidation.ts
> +      console.error(err.toString());
Are we supposed to propogate validation errors to telemetry?

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/parser/yaml-documents.ts
> +  findClosestNode(offset: number, textBuffer: TextBuffer): Node {
Can we add tests for this new function

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/parser/yaml-documents.ts
> +  getNodeFromPosition(positionOffset: number): Node | undefined {
Does this new function need tests?

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/utils/astUtils.ts
> +export function getParent(doc: Document, nodeToFind: Node): Node | undefined {
Should be covered with tests

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/utils/astUtils.ts
> +export function getNodePath(doc: Document, node: Node): readonly (Document | Node | Pair)[] | undefined {
Should be covered with tests

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/utils/strings.ts
> +  return position;
I am not sure why this returns the position here

2021-08-27 23:53 UTC, gorkem commented on src/languageservice/yamlLanguageService.ts
> +  // const completer = new YAMLCompletion(schemaService, clientCapabilities, telemetry);
remove unused code

2021-09-13 08:06 UTC, evidolob commented on src/languageservice/parser/yaml-documents.ts
> +        return;
No, as according to dock `visit.BREAK`: Terminate traversal completely. 
In this case we return undefined which means `Do nothing and continue`

2021-09-16 08:41 UTC, evidolob commented on src/languageservice/parser/yaml-documents.ts
> +  findClosestNode(offset: number, textBuffer: TextBuffer): Node {
Done

2021-09-16 08:41 UTC, evidolob commented on src/languageservice/parser/yaml-documents.ts
> +  getNodeFromPosition(positionOffset: number): Node | undefined {
Yes, I add test for it

2021-09-16 08:41 UTC, evidolob commented on src/languageservice/utils/astUtils.ts
> +export function getParent(doc: Document, nodeToFind: Node): Node | undefined {
Done

2021-09-22 07:11 UTC, gorkem approved these changes

2021-09-24 06:18 UTC, merged