Fix document symbols, when key is not string
redhat-developer/yaml-language-server pull request #594
Opened 2021-11-22 14:31 UTC by evidolob

### What does this PR do?
Fix `yaml.hierarchicalDocumentSymbols.error` error message on telemetry.
That can be caused when mapping key is not string.

### What issues does this PR fix or reference?
none

### Is it tested? How?
with tests.

2021-11-22 14:56 UTC, JPinkney approved these changes

2021-11-22 17:24 UTC, gorkem requested changes

2021-11-22 17:24 UTC, gorkem commented on src/languageservice/services/documentSymbols.ts
> +      if (isScalar(keyNode)) {
Can we remove this first `if`? It is probably covered by else at the end.

2021-11-22 17:24 UTC, gorkem commented on src/languageservice/services/documentSymbols.ts
> +      return `"${name}"`;
What is the case to reach this one? Can we have a test for it ?

2021-11-23 09:06 UTC, gorkem approved these changes

2021-11-23 09:28 UTC, merged