Fix showing the snippets with description
redhat-developer/yaml-language-server pull request #619
Opened 2021-12-14 10:25 UTC by msivasubramaniaan

### What does this PR do?

The fix is showing the snippets with corresponding description

### What issues does this PR fix or reference?

https://github.com/redhat-developer/vscode-yaml/issues/642

### Is it tested? How?
Yes with test cases

2021-12-14 12:20 UTC, evidolob commented
@msivasubramaniaan Could you add test for fix?

2021-12-14 14:06 UTC, JPinkney commented on test/schema.test.ts
> +    it('Default snippet with descritpion', async () => {
```suggestion
    it('Default snippet with description', async () => {
```

2021-12-14 14:06 UTC, JPinkney commented on test/schema.test.ts
> +      assert.strictEqual(result.items.length, 2);
Can you do `assert.equal` on the description value here so that we know it's set correctly

2021-12-14 17:22 UTC, gorkem requested changes
Can you please update the author of these commits? Right now they are signed as `unknown` and I am not sure if `<msivasub@win.redhat.com>` is a valid mail address.

2021-12-15 13:18 UTC, evidolob approved these changes

2021-12-16 12:21 UTC, merged