updated maxMatch value based on oneOf size
redhat-developer/yaml-language-server pull request #623
Opened 2021-12-22 07:49 UTC by msivasubramaniaan

### What does this PR do?

This PR updated the maxMatch value based on the oneOf size. Because there may be a chances that node value matches all the schema which provided under oneOf 

### What issues does this PR fix or reference?
https://github.com/redhat-developer/yaml-language-server/issues/586

### Is it tested? How?
Yes with test cases.

2021-12-22 10:01 UTC, evidolob approved these changes

2021-12-22 16:18 UTC, gorkem requested changes

2021-12-22 16:18 UTC, gorkem commented on src/languageservice/parser/jsonParser07.ts
>            severity: DiagnosticSeverity.Warning,
I do not think the following message is accurrate with this change anymore. It needs an updated message.

2021-12-23 18:02 UTC, gorkem approved these changes

2021-12-23 18:12 UTC, gorkem commented
@evidolob do we need to still address #312?

2022-01-11 07:22 UTC, merged