Schema validation should check the object's oneOf if it has instead of the object type
redhat-developer/yaml-language-server pull request #663
Opened 2022-02-17 13:21 UTC by msivasubramaniaan

### What does this PR do?

The PR will check the oneOf array and do the type check against the schemas mentioned over it if the particular schema object has, instead of directly check the schema object type.

### What issues does this PR fix or reference?

https://github.com/redhat-developer/vscode-yaml/issues/692

### Is it tested? How?
Yes with UT

2022-02-17 13:25 UTC, msivasubramaniaan commented
@evidolob please review this PR

2022-02-19 20:36 UTC, gorkem requested changes

2022-02-19 20:36 UTC, gorkem commented on src/languageservice/parser/jsonParser07.ts
> +      return node.type === schema.type || (schema.type === 'integer' && node.type === 'number' && node.isInteger);
Shouldn't this just call `matchesType` from above? It looks like it is duplicating the code.

2022-02-23 01:58 UTC, gorkem approved these changes

2022-02-23 07:03 UTC, evidolob approved these changes

2022-02-23 07:40 UTC, merged