fixed auto completion not suggest const for array
redhat-developer/yaml-language-server pull request #670
Opened 2022-03-02 11:46 UTC by msivasubramaniaan

### What does this PR do?

Auto completion should not suggest const value from schema for Array

### What issues does this PR fix or reference?

https://github.com/redhat-developer/yaml-language-server/issues/620

### Is it tested? How?

Yes. with UT

2022-03-04 18:08 UTC, gorkem requested changes

2022-03-04 18:08 UTC, gorkem commented on src/languageservice/services/yamlCompletion.ts
> +          this.addSchemaValueCompletions(schema.schema, separatorAfter, collector, {}, isArray);
If this is the only place `isArray` is used can we delay its initialization to inside this `if` block?

2022-03-09 12:53 UTC, evidolob commented on src/languageservice/services/yamlCompletion.ts
> +          const isArray = nodeParent.items.length > 0;
Better to use `Array.isArray()` to check is `nodeParent.items` array

2022-03-09 13:23 UTC, evidolob reviewed
LGTM

2022-03-09 13:23 UTC, evidolob approved these changes
LGTM

2022-03-12 17:02 UTC, gorkem approved these changes
lgtm

2022-03-13 01:08 UTC, merged