Fixed auto complete even parameters not in the specific order
redhat-developer/yaml-language-server pull request #719
Opened 2022-05-27 08:26 UTC by msivasubramaniaan

### What does this PR do?
This PR checks the enum values that matches started characters of node value on auto suggestions

### What issues does this PR fix or reference?
https://github.com/redhat-developer/vscode-yaml/issues/705

### Is it tested? How?

Yes. With existing UT.
![image](https://user-images.githubusercontent.com/93245779/170661337-6e634a42-2a89-493c-82dd-4e6ed3e90fc4.png)

2022-05-28 22:25 UTC, gorkem requested changes
Looking good but do our current tests really cover the case? Wouldn't they already fail if they did?

2022-05-29 14:17 UTC, msivasubramaniaan commented
@gorkem The existing test cases were covered with proper order of schema and not with the irregular order. I will add the testcase for this case as well.

2022-05-30 06:37 UTC, evidolob approved these changes

2022-06-01 14:41 UTC, gorkem approved these changes
LGTM

2022-06-01 14:42 UTC, merged