Fix indentation with extra spaces after cursor.
redhat-developer/yaml-language-server pull request #764
Opened 2022-08-08 20:16 UTC by rickcowan

### What does this PR do?
Fixes an indentation issue when you have trailing spaces after the hyphen.

Given the schema:
```yaml
{
  type: 'object',
  properties: {
    test: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          objA: {
            type: 'object',
            required: ['itemA'],
            properties: {
              itemA: {
                type: 'string',
              }
            }
          }
        }
      }
    }
  }
}
```
The following yaml:
```yaml
test:
  - #________(# = cursor, _ = spaces)
```
Would be autocompleted to:
```yaml
test:
  - objA:
             itemA: 
```
After the fix it autocompletes to:
```yaml
test:
  - objA:
      itemA: 
```
### What issues does this PR fix or reference?
no ref

### Is it tested? How?
Manual and unit test.

2022-08-09 05:48 UTC, msivasubramaniaan commented
@rickcowan can you please add  additional test cases for array of array items as well?

2022-08-09 05:49 UTC, msivasubramaniaan requested changes
@rickcowan can you please add additional test cases for array of array items as well?

2022-08-18 12:19 UTC, gorkem approved these changes
LGTM. 
Thanks for the contribution

2022-08-18 16:32 UTC, msivasubramaniaan approved these changes

2022-08-18 16:32 UTC, merged