merged the hover results
redhat-developer/yaml-language-server pull request #772
Opened 2022-08-29 09:37 UTC by msivasubramaniaan

### What does this PR do?
This PR append the title and description of anyOf schemas while hover

### What issues does this PR fix or reference?
https://github.com/redhat-developer/vscode-yaml/issues/784

### Is it tested? How?
Yes. added UT

2022-09-17 16:28 UTC, gorkem requested changes
This is somehow causing one of the `schemaValidation.ts` tests to fail. I can see it locally and on CI too.

2022-09-18 14:21 UTC, msivasubramaniaan commented
> This is somehow causing one of the `schemaValidation.ts` tests to fail. I can see it locally and on CI too.

The test case was failed due to the recent changes happened on [github-workflow.json](https://json.schemastore.org/github-workflow.json#/definitions/env)

FYR
![image](https://user-images.githubusercontent.com/93245779/190911743-6199d862-bdda-4c48-a25c-e2034c11de3f.png)

2022-09-18 16:22 UTC, gorkem commented
also fixes #779

2022-09-18 16:23 UTC, gorkem approved these changes

2022-09-18 17:04 UTC, merged