suggest valid options from oneOf on code completion
redhat-developer/yaml-language-server pull request #786
Opened 2022-09-26 16:46 UTC by msivasubramaniaan

Signed-off-by: msivasubramaniaan <msivasub@redhat.com>

### What does this PR do?
This PR suggest the valid option on code completion from oneOf

### What issues does this PR fix or reference?
https://github.com/redhat-developer/vscode-yaml/issues/829

### Is it tested? How?
Yes added UT

2022-10-14 14:09 UTC, gorkem requested changes
There is one failing test for me locally. I have kicked the CI and I see the same test failure.

2022-10-18 20:02 UTC, msivasubramaniaan commented
> There is one failing test for me locally. I have kicked the CI and I see the same test failure.

Done

2022-11-08 23:15 UTC, gorkem approved these changes

2022-11-09 00:53 UTC, merged

2022-11-22 19:56 UTC, p-spacek commented on src/languageservice/services/yamlCompletion.ts
> +    const uniqueItems = result.items.filter(
Hello, I have a small note here, not sure if I should create an issue for that...

but this piece of code (and test modifications below) is a little bit hiding another problem that some internal methods are called multiple times from different places with the same result.

for example, some schema.snippets are calculated multiple times

A user can't see any problems (results are merged), but it's not correct.

If you decide to create a task for that, I can try to solve it.

Thanks for your great open-source project!!