848 missing required property value reported as type error
redhat-developer/yaml-language-server pull request #855
Opened 2023-03-02 17:39 UTC by msivasubramaniaan

### What does this PR do?
This PR treats an empty string when no value on string.

### What issues does this PR fix or reference?
https://github.com/redhat-developer/yaml-language-server/issues/848

### Is it tested? How?
Yes. Added UT for this case and updated the existing testcases accordingly

2023-03-02 17:42 UTC, msivasubramaniaan commented on src/languageservice/parser/ast-converter.ts
> +      : new NullObjectASTNodeImpl(parent, node, ...toOffsetLength(node.range));
Introduce `Null Object` node **(type=object and value=null)** when no value instead of `Null node`

2023-03-10 19:09 UTC, gorkem requested changes

2023-03-13 12:13 UTC, msivasubramaniaan commented on test/schemaValidation.test.ts
> +          assert.equal(result.length, 1);
Yes it is expected. When type is `object` but provided as `'null'` string

2023-03-26 00:55 UTC, gorkem commented
While reviewing this, I wanted to verify the parser's behaviour and check the specification. [YAML specification](https://yaml.org/spec/1.2.2/#1032-tag-resolution) explicitly states that empty values are recognized as null. If we introduce this new behaviour for empty values, this will potentially break YAML files deliberately using empty values to indicate null.

2023-10-07 16:59 UTC, gorkem commented
closing this PR as it would break a different usage, which seems to be more inline with the specification.

2023-10-07 16:59 UTC, closed without merging