Update to Prettier 3
redhat-developer/yaml-language-server pull request #909
Opened 2023-08-05 09:33 UTC by remcohaszing

### What does this PR do?

This updates Prettier to version 3.

- Prettier 3 is async, so related functions were made async.
- Code was reformatted using Prettier.
- Prettier now ships their own types, so `@types/prettier` was removed.
- Prettier was moved to `dependencies`. `optionalDependencies` is for dependencies that have a `install` script that may fail. This isn’t the case for Prettier.
- `eslint-plugin-prettier` was updated as well.

Alternatively the formatting functionality could be removed. IMO people should just use Prettier themselves for formatting YAML instead of relying on this `yaml-language-server`.

### What issues does this PR fix or reference?

N/A

### Is it tested? How?

```sh
npm test
```

2023-11-09 20:00 UTC, artola commented
@msivasubramaniaan This would be a nice enhancement to support Prettier v3, otherwise we are forced deliver 2 versions of Prettier within our app.

2024-12-18 13:44 UTC, msivasubramaniaan requested changes
Seeing lots of lint changes. Kindly rebase and raise PR only with affected files

2024-12-18 14:05 UTC, remcohaszing commented
Done, but now CI fails. It’s hard to tell intent, because both ESLint are Prettier are not configured correctly for this repo.

2024-12-19 09:00 UTC, msivasubramaniaan approved these changes
LGTM

2024-12-19 09:00 UTC, merged